<?php return array (
  'sans-serif' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $fontDir . '/Helvetica',
    'bold' => $fontDir . '/Helvetica-Bold',
    'italic' => $fontDir . '/Helvetica-Oblique',
    'bold_italic' => $fontDir . '/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $fontDir . '/ZapfDingbats',
    'bold' => $fontDir . '/ZapfDingbats',
    'italic' => $fontDir . '/ZapfDingbats',
    'bold_italic' => $fontDir . '/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $fontDir . '/Symbol',
    'bold' => $fontDir . '/Symbol',
    'italic' => $fontDir . '/Symbol',
    'bold_italic' => $fontDir . '/Symbol',
  ),
  'serif' => array(
    'normal' => $fontDir . '/Times-Roman',
    'bold' => $fontDir . '/Times-Bold',
    'italic' => $fontDir . '/Times-Italic',
    'bold_italic' => $fontDir . '/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $fontDir . '/Courier',
    'bold' => $fontDir . '/Courier-Bold',
    'italic' => $fontDir . '/Courier-Oblique',
    'bold_italic' => $fontDir . '/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $fontDir . '/DejaVuSans-Bold',
    'bold_italic' => $fontDir . '/DejaVuSans-BoldOblique',
    'italic' => $fontDir . '/DejaVuSans-Oblique',
    'normal' => $fontDir . '/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $fontDir . '/DejaVuSansMono-Bold',
    'bold_italic' => $fontDir . '/DejaVuSansMono-BoldOblique',
    'italic' => $fontDir . '/DejaVuSansMono-Oblique',
    'normal' => $fontDir . '/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $fontDir . '/DejaVuSerif-Bold',
    'bold_italic' => $fontDir . '/DejaVuSerif-BoldItalic',
    'italic' => $fontDir . '/DejaVuSerif-Italic',
    'normal' => $fontDir . '/DejaVuSerif',
  ),
  'metropolis' => array(
    '100' => $fontDir . '/metropolis_100_36395ab487308758bd165242255f5089',
    '100_italic' => $fontDir . '/metropolis_100_italic_ad4d583b5faa3e678f06cfd81ee9bbfa',
    '200_italic' => $fontDir . '/metropolis_200_italic_1af7645912500c4e4554bbe508ce73de',
    '300' => $fontDir . '/metropolis_300_ac2402f4c66d92183c6427fe5f448457',
    '300_italic' => $fontDir . '/metropolis_300_italic_c4b735aebb5d925fdfb46e8341627540',
    'normal' => $fontDir . '/metropolis_normal_66d18198d8fbd3cac82d67c573bed99c',
    'italic' => $fontDir . '/metropolis_italic_51add4e5869ae48f346c97f11538b519',
    '500' => $fontDir . '/metropolis_500_d7257475086739c1fdb8fa02d5e61c97',
    '500_italic' => $fontDir . '/metropolis_500_italic_634d867114078738e302582cfe6a1dfc',
    '600' => $fontDir . '/metropolis_600_83ea2b6ff54b5535ce4b0cf23a4227ae',
    '600_italic' => $fontDir . '/metropolis_600_italic_140ec38247fda00d793170977653841b',
    'bold' => $fontDir . '/metropolis_bold_41976c49ae64667728df5031f3294d10',
    'bold_italic' => $fontDir . '/metropolis_bold_italic_05361282792422c9877088bb08ac1988',
    '800' => $fontDir . '/metropolis_800_9d8ee2a4f51224ccee827addfd3f3201',
    '800_italic' => $fontDir . '/metropolis_800_italic_ef2ef338969e5a89ed80a0db24410f9a',
  ),
) ?>